apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: automation-test-
spec:
  # entrypoint is the name of the template used as the starting point of the workflow
  entrypoint: automation-test
  templates:
  - name: automation-test
    steps:
    - - name: verify
        template: verify
    - - name: stress
        template: stress
  - name: verify
    container:
      image: busybox
      command: [sh, -c]
      args: ["
        x=`curl http://webdemo.default.svc.cluster.local:3000/stress/3 -w '%{size_download}' -so /dev/null`;
        if [ $x -eq '3072' ]; 
        then
          exit 0;
        else
          echo x=$x;
          exit 1;
        fi
      "]
  - name: stress
    container:
      image: ymian/wrk
      command: [./wrk, -t8, -c500, -d2m, --latency, http://webdemo.default.svc.cluster.local:3000/stress/3]